# Generated by Django 6.0.6 on 2026-06-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
                ('detected_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
