# Generated by Django 6.0.6 on 2026-06-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelog',
            name='detected_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vehiclelog',
            name='vehicle_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='vehiclelog',
            index=models.Index(fields=['detected_time', 'vehicle_type'], name='detector_ve_detecte_42f664_idx'),
        ),
    ]
